project:
  type: website
  output-dir: docs

website:
  title: "vinni ott"
  favicon: "./pictures/favicon.png"
  search: false
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: hi

format:
  html:
    theme: zephyr
    css: styles.css
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    toc: true